---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: poojabucket-2
      permission: private # acl: public-read
      policy: "{{ lookup('file','my_bucketpolicy.json') }}"
     # aws_access_key: xxxxxxx
      #aws_secret_key: xxxxxxx
      policy:
        Version:"2012-10-17",
        Statement:[
           {
            Effect: Allow,
            Action: "s3:ListAllMyBuckets",
            Resource:"*"
            },
            {
            Effect: Allow,
            Action:["s3:ListBucket","s3:GetBucketLocation"],
            Resource:"arn:aws:s3:::poojabucket-2"
               },
            {
            Effect: Allow,
            Action:[
                 "s3:PutObject",
                 "s3:PutObjectAcl",
                 "s3:GetObject",
                 "s3:GetObjectAcl",
                 "s3:DeleteObject"
               ],
            Resource":"arn:aws:s3:::poojabucket-2/pooja"
            }
         ]
      state: present
      region: ap-south-1
      versioning: no
      
