---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: ${params.BUCKET_NAME}
     # aws_access_key: xxxxxxx
      #aws_secret_key: xxxxxxx
      policy:
          Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Principal: 
                'AWS' : '{{ 821359796262 }}'
              Action: [
                  's3:ListBucket',
                  's3:DeleteObject',
                  's3:GetObject',
                  's3:PutObject',
                  's3:PutObjectAcl'
              ]
      state: present
      region: ap-south-1
      versioning: no
      
