---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: ${params.BUCKET_NAME}
     # aws_access_key: xxxxxxx
      #aws_secret_key: xxxxxxx
      policy: 
      state: present
      region: ${params.AWS_REGION}
      versioning: no
      
