---
- hosts: localhost
 # connection: local
  #gather_facts: False
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: poojabucket-3
      state: present
      region: ap-south-1
      acl: private # acl: public-read
      policy: "{{ lookup('file','my_bucket_policy.json') }}"
      requester_pays: true
      versioning: no
      tags:
         name: poojabucket-3
         type: example
      
      
      
