---
- hosts: localhost
 # connection: local
  #gather_facts: False
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: poojabucket-3
      aws_access_key: AKIA36PG34ATBCKXIIEO
      aws_secret_key: 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
      state: present
      region: ap-south-1
      acl: private # acl: public-read
      policy: "{{ lookup('file','my_bucket_policy.json') }}"
      #requester_pays: true
      versioning: no
      tags:
         name: poojabucket-3
         type: example
      
      
      
