---
- hosts: localhost
  connection: local 
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: ${params.BUCKET_NAME}
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: ${params.BUCKET_NAME}
         type: example
